"""
Full evaluation script combining:
  - Segmentation (IoU, Dice)
  - Detection via bounding boxes (mean IoU, accuracy @0.5 IoU)
  - Classification using RGB+Mask classifier (top-1 acc, macro F1, confusion matrix)

The mask M used for:
  - bounding boxes
  - classifier input (RGBM)
is generated by the segmentation model and post-processed with the same
largest-connected-component (LCC) logic as in `boundingboxes.py`.

Usage (from project root) on the **overnight weights**:

    # Just run with no arguments (hard-coded to overnight weights):
    python src/evaluate_full.py

    # Or override paths if you really want to:
    python src/evaluate_full.py \
        --data some_other_dataset \
        --segmenter_checkpoint path/to/seg.pt \
        --classifier_checkpoint path/to/rgbm_clf.pt \
        --out results/some_other_dir \
        --vis_samples 8
"""

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader
from PIL import Image as PILImage, ImageDraw, ImageFont
from scipy import ndimage

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.dataloader import GestureDataset, GESTURE_TO_CLASS  # noqa: E402
from src.model_rgbd_segmenter import RGBDSegmenter as HandAnalysisSegmenterModel  # noqa: E402
from src.model_rgbm_roi_crop_classifier import RGBMROICropClassifier as GestureClassificationWithMasksModel  # noqa: E402
from src.model_m_roi_crop_classifier import MROICropClassifier as MaskOnlyClassificationModel  # noqa: E402
from src.utils import (  # noqa: E402
    collate_fn,
    bbox_xyxy_norm_to_pixels,
    compute_iou,
    compute_dice,
    compute_bbox_iou,
)


def parse_args():
    p = argparse.ArgumentParser(description="Full evaluation: segmentation, detection, classification (RGBM)")
    # Defaults are hard-coded to the overnight setup so you can just run:
    #   python src/evaluate_full.py
    p.add_argument(
        "--data",
        type=str,
        default="test_dataset",
        help="Path to dataset root (default: test_dataset)",
    )
    p.add_argument(
        "--segmenter_checkpoint",
        type=str,
        default="weights/overnight/best_rgbd_seg.pt",
        help="Path to trained RGBD segmenter checkpoint "
        "(default: weights/overnight/best_rgbd_seg.pt)",
    )
    p.add_argument(
        "--classifier_checkpoint",
        type=str,
        default="weights/overnight/best_rgbm_clf.pt",
        help="Path to trained RGBM classifier checkpoint "
        "(default: weights/overnight/best_rgbm_clf.pt)",
    )
    p.add_argument(
        "--out",
        type=str,
        default="results/evaluation_overnight",
        help="Output directory for metrics and visualisations "
        "(default: results/evaluation_overnight)",
    )
    p.add_argument("--batch_size", type=int, default=8, help="Batch size for evaluation")
    p.add_argument("--vis_samples", type=int, default=8, help="Number of qualitative examples to save as PNG")
    return p.parse_args()


def largest_component_mask(binary_mask: np.ndarray) -> np.ndarray:
    """
    Keep only the largest connected component in a binary mask.

    Matches the post-processing used in `boundingboxes.py`.
    """
    if binary_mask.sum() == 0:
        return binary_mask

    labeled, num_features = ndimage.label(binary_mask)
    if num_features <= 1:
        return binary_mask

    sizes = ndimage.sum(binary_mask, labeled, index=range(1, num_features + 1))
    largest_label = int(np.argmax(sizes)) + 1
    return (labeled == largest_label).astype(np.uint8)


def overlay_mask_on_image(base_img, mask, color=(255, 0, 0), alpha=0.4):
    """Overlay semitransparent mask on RGB base image."""
    mask = np.clip(mask, 0, 1)
    mask_img = np.zeros_like(base_img, dtype=np.uint8)
    mask_img[..., 0] = color[0]
    mask_img[..., 1] = color[1]
    mask_img[..., 2] = color[2]
    mask_img = (mask_img * mask[..., None]).astype(np.uint8)
    overlay = PILImage.fromarray(mask_img).convert("RGBA")
    base_rgba = PILImage.fromarray(base_img).convert("RGBA")
    blended = PILImage.blend(base_rgba, overlay, alpha)
    return blended


def draw_bbox(draw, bbox, outline=(0, 255, 0), width=3):
    """Draw a bounding box: bbox is (x_min, y_min, x_max, y_max)."""
    if bbox is None:
        return
    x1, y1, x2, y2 = bbox
    draw.rectangle([x1, y1, x2, y2], outline=outline, width=width)


def save_visual_example(
    out_dir,
    idx,
    rgb_tensor,
    gt_mask,
    pred_mask,
    gt_bbox_pixels,
    pred_bbox_pixels,
    gt_gesture_id,
    pred_gesture_id,
):
    """
    Save a qualitative PNG showing RGB, overlayed mask, GT & predicted bboxes,
    and GT vs predicted gesture labels.
    """
    rgb_np = rgb_tensor[:3].cpu().numpy()  # (3,H,W)
    rgb_np = (rgb_np * 255).astype(np.uint8) if rgb_np.max() <= 1.0 else rgb_np.astype(np.uint8)
    rgb_np = np.transpose(rgb_np, (1, 2, 0)).copy()  # (H,W,3)

    h, w = rgb_np.shape[:2]
    gt_mask_np = (gt_mask[0].cpu().numpy() > 0.5).astype(np.uint8)
    pred_mask_np = pred_mask.astype(np.float32)

    # Base image with predicted mask overlayed
    vis_img = overlay_mask_on_image(rgb_np, pred_mask_np, color=(255, 0, 0), alpha=0.45)
    draw_img = vis_img.copy()
    draw = ImageDraw.Draw(draw_img)

    # Draw GT bbox in blue, predicted bbox in green
    draw_bbox(draw, gt_bbox_pixels, outline=(0, 0, 255), width=3)
    draw_bbox(draw, pred_bbox_pixels, outline=(0, 255, 0), width=3)

    # Text: GT and predicted gesture
    font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
    if Path(font_path).exists():
        font = ImageFont.truetype(font_path, size=24)
    else:
        font = ImageFont.load_default()

    gt_name = GESTURE_TO_CLASS.get(int(gt_gesture_id), str(int(gt_gesture_id)))
    pred_name = GESTURE_TO_CLASS.get(int(pred_gesture_id), str(int(pred_gesture_id)))
    text = f"GT: {gt_name} [{int(gt_gesture_id)}] | Pred: {pred_name} [{int(pred_gesture_id)}]"

    text_pos = (10, 10)
    text_size = draw.textbbox(text_pos, text, font=font)
    draw.rectangle(
        [text_size[0], text_size[1], text_size[2] + 8, text_size[3] + 4],
        fill=(0, 0, 0, 180),
    )
    draw.text((text_pos[0] + 3, text_pos[1] + 2), text, fill=(0, 255, 0, 255), font=font)

    out_dir = Path(out_dir) / "vis"
    out_dir.mkdir(parents=True, exist_ok=True)
    save_path = out_dir / f"viz_{idx:02}_gt_{int(gt_gesture_id)}_pred_{int(pred_gesture_id)}.png"
    draw_img.save(save_path)


def main():
    args = parse_args()

    data_root = Path(args.data)
    if not data_root.is_absolute():
        data_root = PROJECT_ROOT / data_root
    if not data_root.exists():
        print(f"ERROR: Data path does not exist: {data_root}")
        sys.exit(1)

    seg_ckpt_path = Path(args.segmenter_checkpoint)
    if not seg_ckpt_path.is_absolute():
        seg_ckpt_path = PROJECT_ROOT / seg_ckpt_path
    if not seg_ckpt_path.exists():
        print(f"ERROR: Segmenter checkpoint not found: {seg_ckpt_path}")
        sys.exit(1)

    clf_ckpt_path = Path(args.classifier_checkpoint)
    if not clf_ckpt_path.is_absolute():
        clf_ckpt_path = PROJECT_ROOT / clf_ckpt_path
    if not clf_ckpt_path.exists():
        print(f"ERROR: Classifier checkpoint not found: {clf_ckpt_path}")
        sys.exit(1)

    # Derive paths to the *other* overnight weights (RGB-only seg + mask-only clf)
    overnight_dir = seg_ckpt_path.parent
    rgb_seg_ckpt_path = overnight_dir / "best_rgb_seg.pt"
    mask_clf_ckpt_path = overnight_dir / "best_m_clf.pt"
    if not rgb_seg_ckpt_path.exists():
        print(f"ERROR: RGB-only segmenter checkpoint not found: {rgb_seg_ckpt_path}")
        sys.exit(1)
    if not mask_clf_ckpt_path.exists():
        print(f"ERROR: Mask-only classifier checkpoint not found: {mask_clf_ckpt_path}")
        sys.exit(1)

    out_dir = Path(args.out)
    if not out_dir.is_absolute():
        out_dir = PROJECT_ROOT / out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    dataset = GestureDataset(str(data_root), transform=None)
    if len(dataset) == 0:
        print("ERROR: No samples in dataset.")
        sys.exit(1)
    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=0,
        collate_fn=collate_fn,
    )

    # Load models
    # RGBD segmenter (uses args.segmenter_checkpoint)
    segmenter_rgbd = HandAnalysisSegmenterModel().to(device)
    seg_ckpt = torch.load(seg_ckpt_path, map_location=device)
    seg_state = seg_ckpt.get("model_state_dict", seg_ckpt)
    segmenter_rgbd.load_state_dict(seg_state, strict=True)
    segmenter_rgbd.eval()

    # RGB-only segmenter (depth channel will be zeroed at inference)
    segmenter_rgb = HandAnalysisSegmenterModel().to(device)
    seg_rgb_ckpt = torch.load(rgb_seg_ckpt_path, map_location=device)
    seg_rgb_state = seg_rgb_ckpt.get("model_state_dict", seg_rgb_ckpt)
    segmenter_rgb.load_state_dict(seg_rgb_state, strict=True)
    segmenter_rgb.eval()

    # RGBM classifier (RGB + mask)
    classifier_rgbm = GestureClassificationWithMasksModel(num_classes=len(GESTURE_TO_CLASS)).to(device)
    clf_ckpt = torch.load(clf_ckpt_path, map_location=device)
    clf_state = clf_ckpt.get("model_state_dict", clf_ckpt)
    classifier_rgbm.load_state_dict(clf_state, strict=True)
    classifier_rgbm.eval()

    # Mask-only classifier
    classifier_mask = MaskOnlyClassificationModel(num_classes=len(GESTURE_TO_CLASS)).to(device)
    mask_ckpt = torch.load(mask_clf_ckpt_path, map_location=device)
    mask_state = mask_ckpt.get("model_state_dict", mask_ckpt)
    classifier_mask.load_state_dict(mask_state, strict=True)
    classifier_mask.eval()

    # Metrics accumulators
    seg_ious = {"rgbd": [], "rgb": []}
    seg_dices = {"rgbd": [], "rgb": []}

    bbox_ious = {"rgbd": [], "rgb": []}
    det_correct = {"rgbd": 0, "rgb": 0}
    det_total = 0
    iou_thresh = 0.5

    num_classes = len(GESTURE_TO_CLASS)

    # Four confusion matrices: 2 segmenters x 2 classifiers
    conf_rgbd_rgbm = np.zeros((num_classes, num_classes), dtype=np.int64)
    conf_rgb_rgbm = np.zeros((num_classes, num_classes), dtype=np.int64)
    conf_rgbd_mask = np.zeros((num_classes, num_classes), dtype=np.int64)
    conf_rgb_mask = np.zeros((num_classes, num_classes), dtype=np.int64)

    cls_counts = {
        "rgbd_rgbm": 0,
        "rgb_rgbm": 0,
        "rgbd_mask": 0,
        "rgb_mask": 0,
    }
    cls_correct = {
        "rgbd_rgbm": 0,
        "rgb_rgbm": 0,
        "rgbd_mask": 0,
        "rgb_mask": 0,
    }

    vis_limit = max(0, int(args.vis_samples))
    vis_saved = 0
    n_samples = 0

    with torch.no_grad():
        for batch in loader:
            inp = batch["input"].to(device)   # (B,4,H,W) RGBD
            mask_gt = batch["mask"]          # (B,1,H,W)
            bbox_gt_norm = batch["bbox"]     # (B,4) normalized XYXY
            gestures = batch["gesture"]      # (B,)

            B = inp.size(0)
            H, W = mask_gt.shape[2], mask_gt.shape[3]
            n_samples += B
            det_total += B

            # --- Segmentation for both segmenters ---
            # RGBD segmenter sees full input
            seg_pred_rgbd = segmenter_rgbd(inp)  # (B,1,h',w')
            # RGB-only segmenter sees depth channel zeroed
            inp_rgb = inp.clone()
            inp_rgb[:, 3:4] = 0.0
            seg_pred_rgb = segmenter_rgb(inp_rgb)

            if seg_pred_rgbd.shape[2] != H or seg_pred_rgbd.shape[3] != W:
                seg_pred_rgbd = F.interpolate(seg_pred_rgbd, size=(H, W), mode="bilinear", align_corners=False)
            if seg_pred_rgb.shape[2] != H or seg_pred_rgb.shape[3] != W:
                seg_pred_rgb = F.interpolate(seg_pred_rgb, size=(H, W), mode="bilinear", align_corners=False)

            seg_prob_rgbd = seg_pred_rgbd.squeeze(1).cpu().numpy()  # (B,H,W)
            seg_prob_rgb = seg_pred_rgb.squeeze(1).cpu().numpy()    # (B,H,W)
            mask_gt_np = (mask_gt.squeeze(1).numpy() > 0.5).astype(np.uint8)

            # For each sample in batch
            for i in range(B):
                gt_mask_i = mask_gt_np[i]
                gt_bbox_pixels = bbox_xyxy_norm_to_pixels(bbox_gt_norm[i], height=H, width=W)
                gt_cls = int(gestures[i].item())

                # ---------- RGBD segmenter ----------
                pm_prob_rgbd = seg_prob_rgbd[i]
                pm_bin_rgbd = (pm_prob_rgbd > 0.5).astype(np.uint8)

                seg_ious["rgbd"].append(compute_iou(pm_bin_rgbd, gt_mask_i))
                seg_dices["rgbd"].append(compute_dice(pm_bin_rgbd, gt_mask_i))

                pm_lcc_rgbd = largest_component_mask(pm_bin_rgbd)

                ys_d, xs_d = np.where(pm_lcc_rgbd > 0)
                if ys_d.size > 0 and xs_d.size > 0:
                    x1_d = int(xs_d.min())
                    y1_d = int(ys_d.min())
                    x2_d = int(xs_d.max())
                    y2_d = int(ys_d.max())
                    pred_bbox_rgbd = (x1_d, y1_d, x2_d, y2_d)
                    bbox_iou_rgbd = compute_bbox_iou(pred_bbox_rgbd, gt_bbox_pixels)
                else:
                    pred_bbox_rgbd = None
                    bbox_iou_rgbd = 0.0

                bbox_ious["rgbd"].append(bbox_iou_rgbd)
                if bbox_iou_rgbd >= iou_thresh:
                    det_correct["rgbd"] += 1

                # ---------- RGB-only segmenter ----------
                pm_prob_rgb = seg_prob_rgb[i]
                pm_bin_rgb = (pm_prob_rgb > 0.5).astype(np.uint8)

                seg_ious["rgb"].append(compute_iou(pm_bin_rgb, gt_mask_i))
                seg_dices["rgb"].append(compute_dice(pm_bin_rgb, gt_mask_i))

                pm_lcc_rgb = largest_component_mask(pm_bin_rgb)

                ys_r, xs_r = np.where(pm_lcc_rgb > 0)
                if ys_r.size > 0 and xs_r.size > 0:
                    x1_r = int(xs_r.min())
                    y1_r = int(ys_r.min())
                    x2_r = int(xs_r.max())
                    y2_r = int(ys_r.max())
                    pred_bbox_rgb = (x1_r, y1_r, x2_r, y2_r)
                    bbox_iou_rgb = compute_bbox_iou(pred_bbox_rgb, gt_bbox_pixels)
                else:
                    pred_bbox_rgb = None
                    bbox_iou_rgb = 0.0

                bbox_ious["rgb"].append(bbox_iou_rgb)
                if bbox_iou_rgb >= iou_thresh:
                    det_correct["rgb"] += 1

                # ---------- Classification ----------
                rgb_frame = inp[i, :3].unsqueeze(0)  # (1,3,H,W)

                # RGBD seg + RGBM classifier
                mask_tensor_rgbd = torch.from_numpy(pm_lcc_rgbd).unsqueeze(0).unsqueeze(0).to(device).float()
                rgbm_rgbd = torch.cat([rgb_frame.to(device), mask_tensor_rgbd], dim=1)  # (1,4,H,W)
                logits_rgbd_rgbm = classifier_rgbm(rgbm_rgbd)
                pred_cls_rgbd_rgbm = int(logits_rgbd_rgbm.argmax(dim=1).item())

                cls_counts["rgbd_rgbm"] += 1
                if pred_cls_rgbd_rgbm == gt_cls:
                    cls_correct["rgbd_rgbm"] += 1
                if 0 <= gt_cls < num_classes and 0 <= pred_cls_rgbd_rgbm < num_classes:
                    conf_rgbd_rgbm[gt_cls, pred_cls_rgbd_rgbm] += 1

                # RGB seg + RGBM classifier
                mask_tensor_rgb = torch.from_numpy(pm_lcc_rgb).unsqueeze(0).unsqueeze(0).to(device).float()
                rgbm_rgb = torch.cat([rgb_frame.to(device), mask_tensor_rgb], dim=1)
                logits_rgb_rgbm = classifier_rgbm(rgbm_rgb)
                pred_cls_rgb_rgbm = int(logits_rgb_rgbm.argmax(dim=1).item())

                cls_counts["rgb_rgbm"] += 1
                if pred_cls_rgb_rgbm == gt_cls:
                    cls_correct["rgb_rgbm"] += 1
                if 0 <= gt_cls < num_classes and 0 <= pred_cls_rgb_rgbm < num_classes:
                    conf_rgb_rgbm[gt_cls, pred_cls_rgb_rgbm] += 1

                # RGBD seg + mask-only classifier
                logits_rgbd_mask = classifier_mask(mask_tensor_rgbd)
                pred_cls_rgbd_mask = int(logits_rgbd_mask.argmax(dim=1).item())

                cls_counts["rgbd_mask"] += 1
                if pred_cls_rgbd_mask == gt_cls:
                    cls_correct["rgbd_mask"] += 1
                if 0 <= gt_cls < num_classes and 0 <= pred_cls_rgbd_mask < num_classes:
                    conf_rgbd_mask[gt_cls, pred_cls_rgbd_mask] += 1

                # RGB seg + mask-only classifier
                logits_rgb_mask = classifier_mask(mask_tensor_rgb)
                pred_cls_rgb_mask = int(logits_rgb_mask.argmax(dim=1).item())

                cls_counts["rgb_mask"] += 1
                if pred_cls_rgb_mask == gt_cls:
                    cls_correct["rgb_mask"] += 1
                if 0 <= gt_cls < num_classes and 0 <= pred_cls_rgb_mask < num_classes:
                    conf_rgb_mask[gt_cls, pred_cls_rgb_mask] += 1

                # --- Visual examples (use RGBD + RGBM path for visuals) ---
                if vis_saved < vis_limit:
                    save_visual_example(
                        out_dir,
                        vis_saved,
                        rgb_tensor=inp[i].cpu(),
                        gt_mask=mask_gt[i],
                        pred_mask=pm_lcc_rgbd,
                        gt_bbox_pixels=gt_bbox_pixels,
                        pred_bbox_pixels=pred_bbox_rgbd,
                        gt_gesture_id=gt_cls,
                        pred_gesture_id=pred_cls_rgbd_rgbm,
                    )
                    vis_saved += 1

    # Aggregate metrics
    seg_mean_iou_rgbd = float(np.mean(seg_ious["rgbd"])) if seg_ious["rgbd"] else 0.0
    seg_mean_dice_rgbd = float(np.mean(seg_dices["rgbd"])) if seg_dices["rgbd"] else 0.0
    seg_mean_iou_rgb = float(np.mean(seg_ious["rgb"])) if seg_ious["rgb"] else 0.0
    seg_mean_dice_rgb = float(np.mean(seg_dices["rgb"])) if seg_dices["rgb"] else 0.0

    det_mean_iou_rgbd = float(np.mean(bbox_ious["rgbd"])) if bbox_ious["rgbd"] else 0.0
    det_acc_rgbd = float(det_correct["rgbd"]) / float(det_total) if det_total > 0 else 0.0
    det_mean_iou_rgb = float(np.mean(bbox_ious["rgb"])) if bbox_ious["rgb"] else 0.0
    det_acc_rgb = float(det_correct["rgb"]) / float(det_total) if det_total > 0 else 0.0

    def macro_f1_from_conf(conf_mat: np.ndarray) -> float:
        f1_per_class = []
        for c in range(num_classes):
            tp = conf_mat[c, c]
            fp = conf_mat[:, c].sum() - tp
            fn = conf_mat[c, :].sum() - tp
            denom = 2 * tp + fp + fn
            if denom > 0:
                f1_per_class.append(2 * tp / denom)
        return float(np.mean(f1_per_class)) if f1_per_class else 0.0

    def acc_from_counts(name: str) -> float:
        return float(cls_correct[name]) / float(cls_counts[name]) if cls_counts[name] > 0 else 0.0

    metrics = {
        "n_samples": int(n_samples),
        "segmentation": {
            "rgbd_segmenter": {
                "mean_iou": seg_mean_iou_rgbd,
                "mean_dice": seg_mean_dice_rgbd,
            },
            "rgb_segmenter": {
                "mean_iou": seg_mean_iou_rgb,
                "mean_dice": seg_mean_dice_rgb,
            },
        },
        "detection": {
            "rgbd_segmenter": {
                "bbox_mean_iou": det_mean_iou_rgbd,
                "bbox_acc_at_0_5": det_acc_rgbd,
            },
            "rgb_segmenter": {
                "bbox_mean_iou": det_mean_iou_rgb,
                "bbox_acc_at_0_5": det_acc_rgb,
            },
        },
        "classification": {
            "rgbd_segmenter_rgbm_classifier": {
                "top1_acc": acc_from_counts("rgbd_rgbm"),
                "macro_f1": macro_f1_from_conf(conf_rgbd_rgbm),
            },
            "rgb_segmenter_rgbm_classifier": {
                "top1_acc": acc_from_counts("rgb_rgbm"),
                "macro_f1": macro_f1_from_conf(conf_rgb_rgbm),
            },
            "rgbd_segmenter_mask_classifier": {
                "top1_acc": acc_from_counts("rgbd_mask"),
                "macro_f1": macro_f1_from_conf(conf_rgbd_mask),
            },
            "rgb_segmenter_mask_classifier": {
                "top1_acc": acc_from_counts("rgb_mask"),
                "macro_f1": macro_f1_from_conf(conf_rgb_mask),
            },
        },
    }

    print("========== Evaluation Results ==========")
    print(f"Samples: {n_samples}")
    print()
    print("RGBD Segmenter:")
    print(f"  Seg  mean IoU : {seg_mean_iou_rgbd:.4f}  Dice: {seg_mean_dice_rgbd:.4f}")
    print(f"  BBox mean IoU : {det_mean_iou_rgbd:.4f}  acc@0.5: {det_acc_rgbd:.4f}")
    print("RGB-only Segmenter:")
    print(f"  Seg  mean IoU : {seg_mean_iou_rgb:.4f}  Dice: {seg_mean_dice_rgb:.4f}")
    print(f"  BBox mean IoU : {det_mean_iou_rgb:.4f}  acc@0.5: {det_acc_rgb:.4f}")
    print()
    print("Pipeline                                       Top-1  Macro-F1")
    print("--------------------------------------------------------------")
    print(
        f"  RGBD seg  + RGBM  clf                       "
        f"{acc_from_counts('rgbd_rgbm'):.4f}    {macro_f1_from_conf(conf_rgbd_rgbm):.4f}"
    )
    print(
        f"  RGB  seg  + RGBM  clf                       "
        f"{acc_from_counts('rgb_rgbm'):.4f}    {macro_f1_from_conf(conf_rgb_rgbm):.4f}"
    )
    print(
        f"  RGBD seg  + Mask  clf                       "
        f"{acc_from_counts('rgbd_mask'):.4f}    {macro_f1_from_conf(conf_rgbd_mask):.4f}"
    )
    print(
        f"  RGB  seg  + Mask  clf                       "
        f"{acc_from_counts('rgb_mask'):.4f}    {macro_f1_from_conf(conf_rgb_mask):.4f}"
    )
    print("=========================================")

    with (out_dir / "metrics.json").open("w") as f:
        json.dump(metrics, f, indent=2)

    # Save confusion matrices
    np.save(out_dir / "confusion_rgbd_rgbm.npy", conf_rgbd_rgbm)
    np.save(out_dir / "confusion_rgb_rgbm.npy", conf_rgb_rgbm)
    np.save(out_dir / "confusion_rgbd_mask.npy", conf_rgbd_mask)
    np.save(out_dir / "confusion_rgb_mask.npy", conf_rgb_mask)


if __name__ == "__main__":
    main()

