"""
RGBM ROI-cropped gesture classifier.

Takes a 4-channel RGB + predicted mask (RGBM) tensor of shape (B, 4, H, W)
and predicts gesture logits of shape (B, num_classes).

The mask channel M is generated by the RGBD segmenter and post-processed
(largest connected component) before concatenation.

The difference between this and MROICropClassifier is that this model also
sees the colour information, so in theory it can use appearance cues too --
things like the orientation of fingers etc. that might be more visible in
colour than just the silhouette. In practice the two models perform similarly,
which is interesting (maybe the mask really does contain all the info needed?).
"""

import torch
import torch.nn as nn


class RGBMEncoder(nn.Module):
    """
    Lightweight CNN encoder for RGBM input (4 channels: R, G, B, M).

    Basically identical to MaskOnlyEncoder but takes 4 input channels.
    The mask channel M acts as a spatial attention signal -- it tells the
    network where the hand is, which should help it focus on the relevant region
    even if the background is cluttered.

    Input should be a 224x224 crop centred on the hand, with the mask channel
    showing the hand silhouette within that crop.
    """

    def __init__(self):
        super().__init__()
        self.features = nn.Sequential(
            # Block 1: 4 channels (RGBM) -> 64, spatial: 224 -> 112
            nn.Conv2d(4, 64, kernel_size=3, stride=1, padding=1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),

            # Block 2: 64 -> 128, 112 -> 56
            nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1, bias=False),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),

            # Block 3: 128 -> 256, 56 -> 28
            nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1, bias=False),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),

            # Block 4: 256 -> 512, 28 -> 14
            nn.Conv2d(256, 512, kernel_size=3, stride=1, padding=1, bias=False),
            nn.BatchNorm2d(512),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.features(x)  # (B, 512, H/16, W/16)


class RGBMROICropClassifier(nn.Module):
    """
    RGBM ROI-cropped gesture classifier.

    Pipeline (training/inference):
        1. Run RGBD segmenter on full frame to get raw probability mask
        2. Threshold at 0.5, apply LCC post-processing to keep largest blob
        3. Find bounding box from that clean mask
        4. Crop a square region (1.2x the bbox size) from both the RGB frame and the mask
        5. Resize crop to 224x224
        6. Stack as (R, G, B, M) -- 4 channels total
        7. Feed into this classifier

    This model sees both colour and shape, whereas MROICropClassifier only sees shape.

    Args:
        num_classes: Number of gesture classes (default 10)
    """

    def __init__(self, num_classes: int = 10):
        super().__init__()
        self.backbone = RGBMEncoder()
        # Global average pool to flatten spatial dims
        self.pool = nn.AdaptiveAvgPool2d(1)
        # Final linear layer mapping 512-dim features to class logits
        self.classifier = nn.Linear(512, num_classes)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: (B, 4, H, W) tensor with channels in order (R, G, B, M)
               RGB channels should be in [0, 1] float
               M channel should be a binary float mask (0.0 or 1.0)

        Returns:
            Logits of shape (B, num_classes) -- raw scores, not softmaxed.
        """
        feats = self.backbone(x)                       # (B, 512, H/16, W/16)
        pooled = self.pool(feats).view(x.size(0), -1)  # (B, 512)
        logits = self.classifier(pooled)               # (B, num_classes)
        return logits


if __name__ == "__main__":
    # Sanity check
    model = RGBMROICropClassifier(num_classes=10)
    dummy = torch.randn(4, 4, 256, 256)  # 4-channel RGBM input, 256x256 (just testing)
    out = model(dummy)
    print("Logits shape:", out.shape)  # should be (4, 10)
